jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
      Em\BackendBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_PROPRIETAIRE:    ROLE_USER, ROLE_HOTELIER
        ROLE_SUPERVISEUR: ROLE_PROPRIETAIRE, ROLE_USER
        ROLE_ADMIN:       ROLE_USER, ROLE_PROPRIETAIRE, ROLE_SUPERVISEUR
        ROLE_SUPER_ADMIN: [ROLE_SUPERVISEUR,ROLE_USER,ROLE_PROPRIETAIRE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # Par-feu du Backoffice
        emclient:
            pattern: ^/mon-compte
            form_login:
                   provider: fos_userbundle
                   csrf_provider: form.csrf_provider
                   login_path: em_client_auth_serviceLogin
                   check_path: em_client_auth_security_check
                   default_target_path: em_client_security # A modifier avec le nom de votre route d'accueil pour le Backoffice
            logout:
                   path:   em_client_auth_security_logout
                   target: em_client_auth_serviceLogin
            anonymous: true

        main:
             pattern: ^/

             form_login:
                   provider: fos_userbundle
                   csrf_provider: form.csrf_provider
                   login_path: em_backend_serviceLogin
                   check_path: fos_user_security_check
                   default_target_path: em_backend_security
             logout:
                   path:   fos_user_security_logout
                   target: em_backend_serviceLogin
             anonymous: true

             remember_me:
                   key:        %secret% # %secret% est un paramètre de parameters.yml


    access_control:
 # Accès à autoriser pour la connexion au FrontOffice
        - { path: ^/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Accès à autoriser pour la connexion au BackOffice
       # - { path: ^/mon-compte/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Protection du Backoffice en sécurisant les liens admin
        - { path: ^/mon-compte/connecte, roles: ROLE_USER }
        - { path: ^/Gestionnaire/access/, roles: ROLE_PROPRIETAIRE}
        - { path: ^/rootemitic/_console, roles: ROLE_ADMIN }


