# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine


    twig.extension.intl:
          class: Twig_Extensions_Extension_Intl #twig\extensions\lib\Twig\Extension\Extension\Intl
          tags:
                - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }