Em\BackendBundle\Entity\Imagesmultipleimmo:
    type: entity
    table: null
    repositoryClass: Em\BackendBundle\Repository\ImagesmultipleimmoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        title:
            type: string
            length: 255
        alt:
            type: string
            length: 255
        dateadd:
            type: datetime

    manyToOne:
         bienimmo:
             targetEntity: Em\BackendBundle\Entity\Bienimmo
             joinColumn:
               name: bienimmo_id
               referencedColumnName: id
             cascade: ["persist"]


    lifecycleCallbacks: {  }
