Em\BackendBundle\Entity\Pays:
    type: entity
    table: null
    repositoryClass: Em\BackendBundle\Repository\PaysRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
