parameters:
   slider_type.class: Em\BackendBundle\Form\Type\SliderType
   slider_handler.class:  Em\BackendBundle\Form\Handler\SliderHandler
   em_backend.SmsApi.class: Em\BackendBundle\Api\SmsApi
   em_backend.CinetPay.class: Em\BackendBundle\Api\CinetPay


services:
     slider_form:
         factory_service: form.factory
         factory_method: createNamed
         class: Symfony\Component\Form\Form
         arguments:
              - slider
              - slider_form

     slider_type:
         class: %slider_type.class%
         tags:
             - { name: form.type, alias: slider_form }

     slider_handler:
          class: %slider_handler.class%
          arguments: [@slider_form ,@request, @doctrine.orm.entity_manager]
          scope: request


     em_backend.SmsApi:
         class: %em_backend.SmsApi.class%

     em_backend.CinetPay:
         class: %em_backend.CinetPay.class%