parameters:
     em_client.Service_Gapi.class: Em\Client\Bundle\Service_Gapi\eloadServiceGapi


services:
#    em_client.example:
#        class: Em\ClientBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

     em_client.gapiCaptcha:
          class: %em_client.Service_Gapi.class%